services:
  - type: web
    name: silentwatch
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
